# Generated by Django 4.2.3 on 2023-08-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('duration in minutes', models.IntegerField(blank=True, null=True)),
                ('noOfQuestions', models.IntegerField(blank=True, null=True)),
                ('marksPerQuestions', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('choice1', models.CharField(blank=True, max_length=300, null=True)),
                ('choice2', models.CharField(blank=True, max_length=300, null=True)),
                ('choice3', models.CharField(blank=True, max_length=300, null=True)),
                ('choice4', models.CharField(blank=True, max_length=300, null=True)),
                ('correctAnswer', models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3'), ('choice4', 'choice4')], max_length=300)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answersheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('endAt', models.DateTimeField(blank=True, null=True)),
                ('marksPerQuestion', models.IntegerField(default=1)),
                ('totalQuestions', models.IntegerField(default=0)),
                ('ended', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.test')),
                ('testTaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.testtaker')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedChoice', models.CharField(blank=True, max_length=8, null=True)),
                ('isCorect', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('notAnswered', 'notAnswered'), ('answered', 'answered'), ('inReview', 'inReview')], default='notAnswered', max_length=15)),
                ('answerSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.answersheet')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.question')),
            ],
        ),
    ]
