# Generated by Django 4.2.3 on 2023-08-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersheet',
            old_name='ended',
            new_name='submited',
        ),
    ]
