# Generated by Django 4.2.3 on 2023-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_rename_ended_answersheet_submited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration in minutes',
            field=models.IntegerField(default=0),
        ),
    ]
