# Generated by Django 4.2.3 on 2023-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_alter_test_duration_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
