# Generated by Django 4.2.3 on 2023-07-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0012_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'testTaker', 'test')},
        ),
    ]
